version: '3.3'

services:
   wordpress:
     image: wordpress:latest
     container_name: rysk-lab_wordpress
     depends_on:
       - db
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
     volumes:
      - "$PWD:/var/www/html"
      - "$PWD/.docker/backup:/tmp/backup"
      - "$PWD/.docker/log:/tmp/log"
     env_file: .env

   db:
     image: mysql:5.7
     container_name: rysk-lab_mysql
     ports:
      - "4306:3306"
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     env_file: .env

volumes:
    db_data:
